### ISSUE TITLE
opening empty text field gives error

### ISSUE THREAD

**Issue by sowirepo** [christiaan/tinymce-codemirror#22]
When the text field is empty, you open the code editor and press 'OK'  without giving input, the editor throws an error and places a `&#x0;` in the input area. It also throws an error
`tinymce.min.js:6 Uncaught IndexSizeError: Failed to execute 'setStart' on 'Range': There is no child at offset 2.`

**Comment by sowirepo** [comment]
it occurs the tinymce option `forced_root_block : false` is set

**Comment by thomich** [comment]
Hey @sowirepo 

i can't reproduce.. please provide more details, code or anything else and steps to reproduce.

try also use: `forced_root_block : ''` in your tiny_mce config option.

thanks
thomi

**Comment by katywings** [comment]
Good morning @thomich 

We had some problems too with `forced_root_block:'p'`
(When pressing ok while not being in a node it has every time created a new p node)

But we found a little hotfix:

In your `function submit()` block we added (at the beginning):

```js
var forced_root_block_orig = editor.settings.forced_root_block;
editor.settings.forced_root_block = "";
```

and at the end of that function:

```js
editor.settings.forced_root_block = forced_root_block_orig;
```

forced_root_block is recommended by tinymce and we like it for the non-dev users!
