### ISSUE TITLE
Removing the cursor code?

### ISSUE THREAD

**Issue by NathanWailes** [christiaan/tinymce-codemirror#23]
Hello,

I'm working on a project where we'd like to not have the cursor code show up, even though that will lose the cursor position. What's the best way to do that?

**Comment by thomich** [comment]
Hey @NathanWailes 

Thanks for contributing... have saw your PR https://github.com/christiaan/tinymce-codemirror/pull/24 and will check and give feedback..

Regards
thomi

**Comment by thomich** [comment]
Hey @NathanWailes 

Tested and merged ;)

nice day
thomi
