### ISSUE TITLE
Uncaught TypeError: Cannot read property 'saveCursorPosition' of undefined

### ISSUE THREAD

**Issue by pankajadhyapak** [christiaan/tinymce-codemirror#27]
hey trying to add this plugin but getting this error on clicking source code menu

**Comment by groovenectar** [comment]
For now, you can just make sure to specify some configuration options for it.

See the config example here: https://github.com/christiaan/tinymce-codemirror#configuration

**Comment by thomich** [comment]
Hello

can't reproduce, even if i don't have a config for it.. default config will be used..
but i will add/update configuration part in readme.

regards
thomi

**Comment by idnovate** [comment]
Fixed #38
