### ISSUE TITLE
Please remove the codemirror-4.8 folder

### ISSUE THREAD

**Issue by tobia** [christiaan/tinymce-codemirror#28]
Hi

Did you intentionally commit a copy of the codemirror source code into this repository? I think it would be better to let users do that, otherwise those who already have a copy of codemirror get a duplicate of the source code. You could maybe link it as a git submodule, so that one could choose to do a shallow clone and not get it.

Also, the package.json file contains:

    "main": "plugins/plugin.js",

but the actual file is at `plugins/codemirror/plugin.js`, so that gives an error too.

**Comment by thomich** [comment]
Hey @tobia 

Thanks for input..
Will change "main" path and check about linking codemirror repo into our project.

I use codemirror-5.8 in my projects, just to inform it's easy to use another version of codemirror... just configuration thing ;)

regards
thomi

**Comment by thomich** [comment]
Hey

have added and tested codemirror as submodule..
i keep codemirror-4.8 folder and also in config.. as user can decide what to use if he installs our plugin into tiny_mce...
also updated readme file..

nice time
thomi
