### ISSUE TITLE
Esc should close the popup

### ISSUE THREAD

**Issue by tobia** [christiaan/tinymce-codemirror#29]
I think Esc, when pressed inside CodeMirror, should close the editing popup, as it does in any other TinyMCE popup.

I'm leaving this issue here as a reminder. I'll send you a PR if/when I manage to look into it.

**Comment by thomich** [comment]
Hello @tobia 

Problem is, if cursor is focused in the source code itself, ESC don't work.
If you click eg. near the OK/Cancel button (eg. left of them) and then press ESC it will work...

It could be that codemirror itself does bind ESC key and also tinymce window manager also bind the ESC.

If you eg. click into source code and press CTRL+F inside codemirror it open the search feature and pressing then ESC will close it...

Sound like ESC inside source code is bound to codemirror itself and ESC outside it is bound to tinymce window manager.

At the moment, i don't know, how to solve...

If any idea, or other input.. or if i'm wrong ;) let me know..

regards
thomi
