### ISSUE TITLE
Problem with CrossDomain iFrame

### ISSUE THREAD

**Issue by simnzz** [christiaan/tinymce-codemirror#3]
I've got a problem with an CrossDomain installation of tinyMCE with the codemirror-plugin enabled.

The source.html cannot be loaded over two different domains (all other plugins doesn't have this issue), it failes with:

Uncaught SecurityError: Blocked a frame with origin "http://TINYMCE_HOSTING_DOMAIN" from accessing a frame with origin "http://CUSTOMER_DOMAIN". Protocols, domains, and ports must match.

Any idea? Can't get it working so far with document.domain = document.domain or other mechanism...

**Comment by thomich** [comment]
Hello @simnzz 

To know, if this still exists:
Can you reproduce your reported issue also with latest TinyMCE and tinymce-codemirror code?

Thanks for your reply

Regards
thomi

**Comment by thomich** [comment]
Hey @simnzz 

If you had time to test, we are interested in your result.. else we will close this issue.

Thanks in advance
thomi

**Comment by thomich** [comment]
Hey @simnzz 

Would be nice, if you give us some feedback...

Many thanks

Regards
thomi

**Comment by frankliang610** [comment]
Hi @thomich, 
Hope you are still maintaining this project.

I've got the same issue when using Chrome to open the HTML source code page.
It says: "Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame." The error was caught in source.html (tinymce = parent.tinymce). A screenshot will be attached to show it. 
![Blocked a frame with origin issue](https://user-images.githubusercontent.com/7367412/57193268-55ad3f80-6f8d-11e9-9f33-8a23eb14efad.png)

I tried to google and fix it but couldn't find any solutions. Hope you could help me with this issue.
Thank you very much.

Here are the detialed info about the versions I am dealing with. 
TinyMCE V4.9.4 with CodeMirror V5.45.0, working on Chrome V73.0.3683.103(Official Build 64bit) 
Firefox V66.0.3 (64-bit) and IE 11 are working well without any problem, though IE needs to click the javascript activate button manually every time. 

Thank you again.
Kind regards,
frank

**Comment by thomich** [comment]
Hey @frankliang610 

Yes i'm still in ;) but the time....
Will try to repoduce the issue and give feedback, but i need time, as lot's of other projects are pending.

Regards
thomi

**Comment by frankliang610** [comment]
Hi @thomich 

Thank you for your reply.
Yes, I understand it and I am very appreciated that you will spare your time to take a look at the issue.

Thank you again. (^ ^)

Kind regards,
frank

**Comment by thomich** [comment]
Please check: https://github.com/christiaan/tinymce-codemirror/issues/46

**Comment by Daijobou** [comment]
@simnzz @frankliang610 @thomich 
In file **source.html** you must add on top `document.domain = 'your-domain.tld';`
Here should codemirror plugin have a setting, so I can set _domain_-value via tinymce-codemirror settings.

**Comment by thomich** [comment]
please check our new repo

https://gitlab.com/tinymce-plugins/tinymce-codemirror

report a issue ther or even better, create a merge request 😊👍
