### ISSUE TITLE
missing script: prepublish

### ISSUE THREAD

**Issue by elfeffe** [christiaan/tinymce-codemirror#30]
I can't install it

I have opened a ticket here
https://github.com/npm/npm/issues/16367

I don't know if it's NPM problem or this repository.

**Comment by elfeffe** [comment]
This is the error, it's in your package
https://github.com/npm/npm/issues/16367#issuecomment-294568958

**Comment by christiaan** [comment]
I just followed the instructions in the README like this.

```sh
git clone https://github.com/christiaan/tinymce-codemirror.git
cd tinymce-codemirror
npm install
# this is not even needed but listed in the README so I did it anyway: 
npm install uglify-js

npm run prepublish
```

Without any error. Why are you trying to run prepublish?

**Comment by elfeffe** [comment]
I read the README.Md and I don't see the instructions that you said.
Anyway, I will try it.
I try to run prepublish because the documentation, and your last line, says

> npm run prepublish

**Comment by christiaan** [comment]
In which directory are you running that command? What `npm run prepublish` does is look in the current directory if there is a `package.json` file and run the prepublish script that is defined in that json file. See [npm run-script](https://docs.npmjs.com/cli/run-script)

I see that the README says it is needed to run the prepublish script of CodeMirror (listed in the requirements). When I look in the [CodeMirror repo](https://github.com/codemirror/CodeMirror) it has a package.json with a prepublish script which indeed should be run to build CodeMirror.
