### ISSUE TITLE
Permission to push?

### ISSUE THREAD

**Issue by peterw8102** [christiaan/tinymce-codemirror#34]
Can I have permission to post a new branch/PR with possible changes? Don't really want to create yet another fork of this and yours seems the most recent!

Thanks you!

**Comment by christiaan** [comment]
First thanks for willing to contribute to this project :+1: !

Creating a fork is the way git works. Best is to create a fork with a branch that contains your changes.
Then use github to create PR (Pull Request) from your branch to this repo's master branch.

See this [github guide](https://guides.github.com/activities/forking/) on the workflow described above.

Beside the technicalities of creating a pull request I also like this [article by Mark Seemann](http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/) about the contents of a good pull request.
Especially the part about not putting multiple changes in a single request.

Thanks again

**Comment by peterw8102** [comment]
@christiaan Thank you for the pointer to that article, very useful. I wasn't aware of that work flow and haven't previously contributed to other people's projects. Will follow that!
