### ISSUE TITLE
Opening and closing the source editor adds tags with non-breaking spaces to top of content

### ISSUE THREAD

**Issue by cdaveb** [christiaan/tinymce-codemirror#37]
I've noticed that there seems to be an issue where if you open and then close the codemirror source editor in TinyMCE it seems to insert empty tags (p tags if forced_root_block is not set to div, otherwise div tags) at the top of the content. This only seems to happen if you close the editor and your cursor is not within an existing tag. It will continue to keep inserting blank tags at the start (i.e. `<p>&nbsp;</p>` or `<div>&nbsp;</div>`) at the top of the source everytime you close and reopen the editor. I can't reproduce this issue in the standard TinyMCE source editor- it only happens when I use codemirror.

For example, see these pictures of what happens each time you reopen the source editor and close it.
![screen shot 2018-03-06 at 2 08 57 pm](https://user-images.githubusercontent.com/6133808/37061342-11be0e60-2148-11e8-9407-12386d28f907.png)

![screen shot 2018-03-06 at 2 09 21 pm](https://user-images.githubusercontent.com/6133808/37061350-15d6fe44-2148-11e8-8aa3-467e3a8ae531.png)

![screen shot 2018-03-06 at 2 09 38 pm](https://user-images.githubusercontent.com/6133808/37061355-19b5cc2a-2148-11e8-8d2c-ddc2a0623495.png)

**Comment by donfusilli** [comment]
Hi @cdaveb, I'm running into this same issue. Did you implement a workaround for this?

**Comment by vince2corte** [comment]
Hi !
I have the same problem.
I use TinyMCE 4.9.3 - CodeMirror 5.44.0 - Firefox 65.
Any idea to solve that problem ? Thanx !

Edit :
Well, I think I solved the problem with a little conf of TynyMCE. I added thoses lines :
```
entity_encoding: "raw",
force_p_newlines : true,
forced_root_block : "",
```
I don't know if "raw" is required, but I didn't want HTML entities in my code, so it'just good for me. Hope this will help !

**Comment by thomich** [comment]
Please check: https://github.com/christiaan/tinymce-codemirror/issues/46
