### ISSUE TITLE
cannot load codemirror tinymce

### ISSUE THREAD

**Issue by SGD-DEV** [christiaan/tinymce-codemirror#41]
i get this when open in tiny mce

window opens but see only this message
**CodeMirror not found in "codemirror/", aborting...**

what is wrong?

i have unzip Codemirror in tinymce->plugins -> codemirror-> codemirror

**Comment by kabircse** [comment]
You did not follow the instruction properly.
5. Unpack codemirror-latest.zip inside the plugins/codemirror folder that was just created. A folder named codemirror-4.8 (or similar) will be created. Renamed the created folder to CodeMirror.

It will solve your problem.
