### ISSUE TITLE
support for tinymce5?

### ISSUE THREAD

**Issue by toastbrotch** [christiaan/tinymce-codemirror#43]
as tinymce5 is RC2, what about supporting it? some things changed... and this version is not working. was not yet able to fix it myself, so i ask here... anyone managed?

**Comment by tvaliasek** [comment]
see #44

**Comment by tvaliasek** [comment]
Pull requests to the original repository are ignored by the author, so I will continue to update forked repo. https://github.com/tvaliasek/tinymce-codemirror

**Comment by thomich** [comment]
will merge the PR's... was ooo... sorry...
