### ISSUE TITLE
Embedding inline?

### ISSUE THREAD

**Issue by brettz9** [christiaan/tinymce-codemirror#47]
Hi,

Thanks for maintaining this.

I am wondering if there was any chance you looked into embedding CodeMirror inline, so there was not even need for an external window, i.e., one could edit the code within code blocks embedded inside the regular TinyMCE editor (in place of what only supports read-only display)?

**Comment by thomich** [comment]
Hello @brettz9 

Can you please open a issue on our new repo. @ gitlab, as we can't reach original maintainer we moved to gitlab:
https://gitlab.com/tinymce-plugins/tinymce-codemirror

Many thanks

Regards
thomi
