### ISSUE TITLE
z-index issue with table panel and source code dialog

### ISSUE THREAD

**Issue by Daijobou** [christiaan/tinymce-codemirror#6]
In my tinymce 4.3.7 the table panel popup have a higher z-index than the source code dialog z-index.

See: https://picload.org/image/wpggcoc/zindexxt.png

Result: table panel is over source code dialog visible.

That problem comes with 
`
            external_plugins: {
            "codemirror": "path/plugins/codemirror-1.4/plugin.min.js"
            },
`

**Comment by thomich** [comment]
same problem with latest tinymce 4.4.1 and codemirror plugin...

seams, table panel should be closed before opening codemirror dialog..
if using default code plugin in tinymce it works...

**Comment by Daijobou** [comment]
Yes, something like https://www.tinymce.com/docs/api/tinymce.ui/tinymce.ui.floatpanel/#hideall
tinymce.ui.FloatPanel.hideAll(); 

This not work for me, after add in this line https://github.com/christiaan/tinymce-codemirror/blob/master/plugins/codemirror/source.html#L126 the FloatPanel is still not closed.

EDIT: I found a workaround. instead add this lines:
`tinymce.each(editor.contextToolbars, function(toolbar) {
    if (toolbar.panel) {
        toolbar.panel.hide();
    }
});`
After open souce-editor the FloatPanel now disappear.

**Comment by thomich** [comment]
also added the line provided by @Daijobou into source.html before line 126 and it works now...

![selection_013](https://cloud.githubusercontent.com/assets/4398840/17801147/9ad831d4-65e8-11e6-8255-71cf3f9f50a8.png)

hope someone of the tinymce-codemirror team will fix this issue, so we have latest version..

many thanks

**Comment by christiaan** [comment]
If you could create a pullrequest with this change I'd be happy to merge it.

**Comment by thomich** [comment]
this issue can be closed, right?

**Comment by WebVeteran** [comment]
Yeah this looks good to me. Opening the source closes other panels. There might be a _better_ fix though. If you open a menu and then click source, those menus close immediately. The panels however, with this fix, only close after the source is loaded. It would better to put the panel closer function before opening the source view.

**Comment by thomich** [comment]
closing this issue.. if we find better solution, lets open a PR, check and merge it ;)
