### ISSUE TITLE
HTML get damaged with replace URL in Editor 

### ISSUE THREAD

**Issue by Daijobou** [christiaan/tinymce-codemirror#9]
Is this a Plugin bug, TinyMCE bug or a problem with CodeMirror itself?

https://github.com/codemirror/CodeMirror/issues/4145

**Comment by christiaan** [comment]
This seems to be a bug related wit this plugin. It could be a TinyMCE bug but definitely not a CodeMirror bug.

**Comment by Daijobou** [comment]
Maybe here is a problem with this line?
https://github.com/christiaan/tinymce-codemirror/blob/master/plugins/codemirror/source.html#L197

Because this is included (bold text) after submit source-code
&lt;a href="file.jpg**&lt;span id=">**" target="_blank"&gt;URL1&lt;/a&gt;

**Comment by thomich** [comment]
Hello @Daijobou 

Can you reproduce your reported issue also with latest TinyMCE and tinymce-codemirror code?

Thanks for your reply

Regards
thomi

**Comment by Daijobou** [comment]
Yes.

**Comment by thomich** [comment]
I tested this issue with:
tiny_mce: 4.4.2
current codemirror plugin (master) for tiny_mce
codemirror i use for the plugin: codemirror-5.8

i followed this steps and can't reproduce:

1 add this code into source editor

```
<a
   href="URL1" target="_blank">Text</a>
```

![selection_002](https://cloud.githubusercontent.com/assets/4398840/20212100/c355e088-a801-11e6-889d-499525bb1095.png)

2 click ok in source editor and check link in tiny_mce

![selection_004](https://cloud.githubusercontent.com/assets/4398840/20212107/c8c9b9c2-a801-11e6-9c4f-25b88693a638.png)

3 reopen source editor and check source code

![selection_005](https://cloud.githubusercontent.com/assets/4398840/20212114/d4f8e4ac-a801-11e6-8593-482d44adda8f.png)

4 add real URL in source editor

![selection_006](https://cloud.githubusercontent.com/assets/4398840/20212134/e390ef0a-a801-11e6-8379-a7ac95bef03a.png)

5 check again link with tiny_mce link editor.. all success

if you can provide more information, more details, let us know.. we will try to help ;)

regards
thomi

**Comment by Daijobou** [comment]
Thanks, but your step two is wrong. :)
1. open source editor
2. edit in source editor the URL with a real one
3. close source editor

result in tinymce looks like:

> " target="_blank">Text

**Comment by thomich** [comment]
Yeah i see what you mean...

whats the reason why you use two lines for adding a link?
do you follow any special coding style like PEP 8 or similar?

workaround can be:

instead of this:

```
<a
   href="URL1" target="_blank">Text</a>

```

add it like this

`<a href="URL1" target="_blank">Text</a>`

**Comment by Daijobou** [comment]
I never use this way to add links, but someone have do it and report the bug to me and I report it her, because its a bug in any way. I have said him the same, to use a single line. ;)

**Comment by thomich** [comment]
okies...

have checked with default tiny_mce code editor and there it works...

climbing down the codemirror plugin code to find out the issue ;)

will update here..

thomi
